/**
 * Supabase Edge Function: save_chat_turn
 *
 * **STATUS: DEPLOYED AND ACTIVE** ✅
 * This is the production version deployed to Supabase.
 *
 * Purpose: Save conversation turns with automatic memory classification
 * Features: Vector embeddings + gravity score classification (impact + intimacy) + entity extraction
 * Author: AI Engineer (Temporal Decay Feature - Worktree 2)
 * Date: 2025-11-24
 * Last Modified: 2025-11-25
 *
 * SECURITY: All API keys (OpenAI, Supabase) are server-side environment variables.
 * Never expose credentials to client code.
 *
 * Other Versions:
 * - index_v2_calibrated.ts: Experimental calibrated version (NOT DEPLOYED)
 * - index_v3_tiers.ts: Experimental tier-based version (NOT DEPLOYED)
 */

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { classifyMemory, type ClassificationResult } from '../_shared/memory-classifier.ts';
import { extractEntities, saveEntitiesWithMentions, savePreferences } from '../_shared/entity-extractor.ts';
import { HuggingFaceClient } from '../_shared/huggingface-client.ts';

// Platform normalization (inline — Deno edge functions can't import from client src/)
const VALID_PLATFORMS = new Set(['chatgpt', 'claude', 'cli', 'claude-code']);
type Platform = 'chatgpt' | 'claude' | 'cli' | 'claude-code';
function normalizePlatform(p: string | undefined): Platform {
  if (p && VALID_PLATFORMS.has(p)) return p as Platform;
  return 'chatgpt';
}

// CORS headers for browser requests
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Initialize Supabase client at module level for connection pooling
// Service role key bypasses RLS - filtering is done in queries
const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const supabase = createClient(supabaseUrl, supabaseServiceKey);

// Initialize HuggingFace client at module level
const hfApiKey = Deno.env.get('HUGGINGFACE_API_KEY');
if (!hfApiKey) {
  throw new Error('HUGGINGFACE_API_KEY environment variable not configured');
}
const hfClient = new HuggingFaceClient(hfApiKey);

interface SaveChatTurnRequest {
  content: string;
  turn_range?: string;
  conversation_id?: string;
  platform?: 'chatgpt' | 'claude' | 'cli';
  speakers: string[];
  turn_count?: number;
  start_timestamp?: number;
  end_timestamp?: number;
  topics?: string[];
  hypothetical_questions?: string[];
  embedding: number[];  // Qwen3-Embedding-8B (4096 dimensions)
  user_id: string;
}

interface SaveChatTurnResponse {
  success: boolean;
  id?: string;
  classification?: {
    impact_score: number;
    intimacy_level: number;
    reasoning: string;
  };
  entities_extracted?: number;
  error?: string;
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    // 1. Parse request body
    const requestData: SaveChatTurnRequest = await req.json();

    // Extract user from JWT if present (authenticated mode)
    const authHeader = req.headers.get('Authorization');
    if (authHeader?.startsWith('Bearer ') && authHeader.length > 50) {
      try {
        const { data: { user }, error } = await supabase.auth.getUser(
          authHeader.slice(7),
        );
        if (user && !error) {
          requestData.user_id = user.id; // Override with authenticated user ID
          console.log(`JWT user extracted: ${user.id}`);
        }
      } catch (jwtErr) {
        console.warn('JWT extraction failed, using body user_id:', (jwtErr as Error).message);
      }
    }

    // 2. Validate required fields
    if (!requestData.content || requestData.content.trim().length === 0) {
      throw new Error('content is required and cannot be empty');
    }

    if (!requestData.speakers || requestData.speakers.length === 0) {
      throw new Error('speakers array is required and cannot be empty');
    }

    // If an embedding is not supplied, generate one using HuggingFace.
    if (!requestData.embedding) {
      if (!hfApiKey) {
        throw new Error('HF_API_KEY environment variable not configured. Cannot generate embedding.');
      }
      // Generate embedding from the content text
      const generated = await hfClient.generateEmbeddings(requestData.content);
      // generateEmbeddings returns an array of embeddings; we expect a single input
      requestData.embedding = generated[0];
    } else if (!Array.isArray(requestData.embedding) || requestData.embedding.length === 0) {
      throw new Error('embedding must be a non‑empty array');
    }

    // Ensure user_id is a valid UUID; generate one if missing or malformed
    // Track if we auto-generated it (user doesn't exist in auth.users)
    let userIdAutoGenerated = false;
    if (!requestData.user_id || !/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$/.test(requestData.user_id)) {
      requestData.user_id = crypto.randomUUID();
      userIdAutoGenerated = true;
      console.log('user_id auto-generated (entity extraction will be skipped)');
    }

    // 3. Get environment variables (SERVER-SIDE ONLY)
    const openaiApiKey = Deno.env.get('OPENAI_API_KEY');
    if (!openaiApiKey) {
      throw new Error('OPENAI_API_KEY environment variable not configured');
    }

    // 4. Run gravity classification and entity extraction in parallel
    console.log('Running parallel classification and entity extraction...');
    const [gravityResult, entityResult] = await Promise.allSettled([
      classifyMemory({
        content: requestData.content,
        speakers: requestData.speakers,
        topics: requestData.topics
      }, openaiApiKey),

      extractEntities({
        content: requestData.content,
        speakers: requestData.speakers
      }, openaiApiKey)
    ]);

    // Handle results independently (fault isolation)
    let classification: ClassificationResult;
    if (gravityResult.status === 'fulfilled') {
      classification = gravityResult.value;
    } else {
      classification = { impact_score: 0, intimacy_level: 0, reasoning: 'Classification failed' };
    }

    let entities: any[];
    let preferences: any[] = [];
    if (entityResult.status === 'fulfilled') {
      entities = entityResult.value.entities;
      preferences = entityResult.value.preferences;
    } else {
      entities = [];
    }

    // Log failures
    if (gravityResult.status === 'rejected') {
      console.warn('Gravity classification failed:', gravityResult.reason);
    }

    if (entityResult.status === 'rejected') {
      console.warn('Entity extraction failed:', entityResult.reason);
    }

    console.log(`Classification result: impact=${classification.impact_score}, intimacy=${classification.intimacy_level}`);
    console.log(`Entity extraction result: ${entities.length} entities found`);

    // 6. Insert into database with classification scores
    const { data, error } = await supabase
      .from('chat_turns')
      .insert({
        content: requestData.content,
        turn_range: requestData.turn_range || '1-1',  // Default to single turn
        conversation_id: requestData.conversation_id || crypto.randomUUID(),
        platform: normalizePlatform(requestData.platform),
        speakers: requestData.speakers,
        turn_count: requestData.turn_count || 1,  // Default to 1 turn
        start_timestamp: requestData.start_timestamp || Date.now(),
        end_timestamp: requestData.end_timestamp || Date.now(),
        topics: requestData.topics,
        hypothetical_questions: requestData.hypothetical_questions,
        embedding: `[${requestData.embedding.join(',')}]`,  // PostgreSQL vector format
        user_id: requestData.user_id,
        // NEW GRAVITY COLUMNS
        impact_score: classification.impact_score,
        intimacy_level: classification.intimacy_level,
        last_accessed: new Date().toISOString(),
        access_count: 0,
        gravity_score: null  // Will be computed during retrieval
      })
      .select('id')
      .single();

    if (error) {
      throw new Error(`Database insert failed: ${error.message}`);
    }

    // 7. Save entities if extraction succeeded AND user_id is real (not auto-generated)
    // Skip if user_id was auto-generated because it doesn't exist in auth.users
    // (entities table has FK constraint: user_id REFERENCES auth.users(id))
    if (entities.length > 0 && !userIdAutoGenerated) {
      await saveEntitiesWithMentions(
        entities,
        data.id,
        requestData.conversation_id || data.id,
        requestData.user_id,
        supabase,
        hfClient
      );
      console.log(`Saved ${entities.length} entities for chat turn ${data.id}`);

      // Mark chat_turn as having entities extracted (for backfill tracking)
      await supabase
        .from('chat_turns')
        .update({ entities_extracted: true })
        .eq('id', data.id);
    } else if (entities.length > 0 && userIdAutoGenerated) {
      console.log(`Skipped saving ${entities.length} entities (user_id auto-generated, FK would fail)`);
    }

    // 7b. Save preferences if extraction succeeded AND user_id is real
    let preferencesSaved = 0;
    if (preferences.length > 0 && !userIdAutoGenerated) {
      preferencesSaved = await savePreferences(preferences, data.id, requestData.user_id, supabase);
      // Mark preferences as extracted
      await supabase
        .from('chat_turns')
        .update({ preferences_extracted: true })
        .eq('id', data.id);
    }

    // 8. Return success response
    const response: SaveChatTurnResponse = {
      success: true,
      id: data.id,
      classification: {
        impact_score: classification.impact_score,
        intimacy_level: classification.intimacy_level,
        reasoning: classification.reasoning
      },
      entities_extracted: entities.length,
      preferences_saved: preferencesSaved
    };

    return new Response(
      JSON.stringify(response),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200
      }
    );

  } catch (error) {
    console.error('Error in save_chat_turn:', error);

    const errorResponse: SaveChatTurnResponse = {
      success: false,
      error: error.message || 'Unknown error occurred'
    };

    return new Response(
      JSON.stringify(errorResponse),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500
      }
    );
  }
});

/*
 * USAGE EXAMPLE (from client-side code):
 *
 * const response = await fetch('https://your-project.supabase.co/functions/v1/save_chat_turn', {
 *   method: 'POST',
 *   headers: {
 *     'Content-Type': 'application/json',
 *     'Authorization': `Bearer ${SUPABASE_ANON_KEY}`
 *   },
 *   body: JSON.stringify({
 *     content: "I had a great training session with my personal trainer Jennifer today. She helped me work on my deadlift form.",
 *     speakers: ['User', 'Assistant'],
 *     topics: ['fitness', 'training'],
 *     embedding: [...], // 4096-dim vector from Qwen3-Embedding-8B (or omit to auto-generate)
 *     user_id: '...'
 *   })
 * });
 *
 * Expected response:
 * {
 *   "success": true,
 *   "id": "uuid",
 *   "classification": {
 *     "impact_score": 15,
 *     "intimacy_level": 1,
 *     "reasoning": "Routine fitness activity with service provider"
 *   },
 *   "entities_extracted": 2
 * }
 */
