/**
 * Firefox Compatibility Tests
 *
 * Tests:
 * 1. Firefox manifest generation produces valid structure
 * 2. Browser compat module detects runtime correctly
 * 3. MAIN-world content script handling
 * 4. OAuth flow fallback
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..', '..');

// ==========================================================================
// 1. Firefox Manifest Structure
// ==========================================================================
describe('Firefox Manifest', () => {
  const manifestPath = join(projectRoot, 'manifest-firefox.json');

  it('should exist (generated by build:firefox)', () => {
    expect(existsSync(manifestPath)).toBe(true);
  });

  let manifest;
  beforeEach(() => {
    manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
  });

  it('should be MV3', () => {
    expect(manifest.manifest_version).toBe(3);
  });

  it('should have browser_specific_settings.gecko', () => {
    expect(manifest.browser_specific_settings).toBeDefined();
    expect(manifest.browser_specific_settings.gecko).toBeDefined();
    expect(manifest.browser_specific_settings.gecko.id).toBe('kyt-memory@kyt.app');
    expect(manifest.browser_specific_settings.gecko.strict_min_version).toBe('109.0');
  });

  it('should NOT have minimum_chrome_version', () => {
    expect(manifest.minimum_chrome_version).toBeUndefined();
  });

  it('should use background.scripts array (not service_worker)', () => {
    expect(manifest.background.service_worker).toBeUndefined();
    expect(manifest.background.scripts).toBeDefined();
    expect(manifest.background.scripts).toContain('background.js');
    expect(manifest.background.type).toBe('module');
  });

  it('should NOT have world: "MAIN" in any content_script', () => {
    for (const cs of manifest.content_scripts) {
      expect(cs.world).toBeUndefined();
    }
  });

  it('should NOT have identity permission', () => {
    expect(manifest.permissions).not.toContain('identity');
  });

  it('should retain all host_permissions from Chrome manifest', () => {
    const chromeManifest = JSON.parse(
      readFileSync(join(projectRoot, 'manifest.json'), 'utf-8')
    );
    expect(manifest.host_permissions).toEqual(chromeManifest.host_permissions);
  });

  it('should retain all content_scripts (minus world)', () => {
    expect(manifest.content_scripts.length).toBeGreaterThanOrEqual(2);
    // ChatGPT content script
    const chatgpt = manifest.content_scripts.find(cs =>
      cs.js?.some(j => j.includes('chatgpt'))
    );
    expect(chatgpt).toBeDefined();
    // Claude content scripts
    const claude = manifest.content_scripts.filter(cs =>
      cs.js?.some(j => j.includes('claude'))
    );
    expect(claude.length).toBeGreaterThanOrEqual(1);
  });

  it('should retain action popup config', () => {
    expect(manifest.action).toBeDefined();
    expect(manifest.action.default_popup).toBe('popup/popup.html');
  });

  it('should retain web_accessible_resources', () => {
    expect(manifest.web_accessible_resources.length).toBeGreaterThanOrEqual(2);
  });
});

// ==========================================================================
// 2. Browser Compat Module
// ==========================================================================
describe('Browser Compat Module', () => {
  it('should detect Chrome environment (no browser global)', async () => {
    // Default test env has no `browser` global
    delete globalThis.browser;
    // Re-import to get fresh detection
    const { isFirefox } = await import('../../src/browser-compat.js');
    // In test env without browser global, should be false
    expect(isFirefox).toBe(false);
  });

  it('should export executeScript function', async () => {
    const mod = await import('../../src/browser-compat.js');
    expect(typeof mod.executeScript).toBe('function');
  });

  it('should export launchAuthFlow function', async () => {
    const mod = await import('../../src/browser-compat.js');
    expect(typeof mod.launchAuthFlow).toBe('function');
  });
});

// ==========================================================================
// 3. Chrome manifest vs Firefox manifest diff
// ==========================================================================
describe('Chrome vs Firefox Manifest Diff', () => {
  let chrome, firefox;

  beforeEach(() => {
    chrome = JSON.parse(readFileSync(join(projectRoot, 'manifest.json'), 'utf-8'));
    firefox = JSON.parse(readFileSync(join(projectRoot, 'manifest-firefox.json'), 'utf-8'));
  });

  it('should have same name and version', () => {
    expect(firefox.name).toBe(chrome.name);
    expect(firefox.version).toBe(chrome.version);
  });

  it('should have same description', () => {
    expect(firefox.description).toBe(chrome.description);
  });

  it('Firefox should have fewer permissions (no identity)', () => {
    expect(firefox.permissions.length).toBeLessThan(chrome.permissions.length);
    const diff = chrome.permissions.filter(p => !firefox.permissions.includes(p));
    expect(diff).toEqual(['identity']);
  });

  it('should have same number of content_scripts', () => {
    expect(firefox.content_scripts.length).toBe(chrome.content_scripts.length);
  });
});
